dadk支持预编译源+代码源支持从Archive导入
DragonOS-Community/DADK pull request #10
Opened 2023-07-12 11:03 UTC by Chiichen

dadk支持预编译源+代码源支持从Archive导入

2023-07-12 17:04 UTC, fslongjin commented on LICENSE
所有文件的权限发生了改变，需要chmod切换回去

2023-07-12 17:07 UTC, fslongjin commented on src/executor/source.rs
> +    pub fn install(&self, target_dir: &CacheDir) -> Result<(), String> {
这个函数的命名有歧义，让人以为是install阶段执行的

2023-07-12 17:07 UTC, fslongjin commented on src/executor/mod.rs
> +                        let mut cmd = "cp -r ".to_string();
拷贝文件好像可以用标准库自带的函数？

2023-07-12 17:09 UTC, fslongjin commented on src/executor/source.rs
> +        info!("downloading {:?}", archive_name);
dadk里面导入的`reqwest`库，可以实现下载文件等网络功能，不需要使用wget。因为使用wget的话就多了一个外部依赖项了。

2023-07-12 17:11 UTC, fslongjin commented on src/executor/source.rs
> +                cmd += "unzip ";
同样的，这里用压缩库来解压。因为有些最小化安装的系统上面，没有unzip命令。

2023-07-12 17:11 UTC, fslongjin commented on src/executor/source.rs
> +            let mut cmd = Command::new("rm");
删除文件的操作也使用rust标准库的函数来做。

2023-07-12 17:12 UTC, fslongjin commented on src/executor/source.rs
> +            let cmd = "cd *;mv -f ./.[!.]* ../../;mv -f ./* ../../".to_string();
这个操作如果能够使用rust标准库的，就不要手写命令，不然可能有一些奇怪错误。

2023-07-12 17:12 UTC, fslongjin commented on src/executor/source.rs
> +            let mut cmd = "rm -rf ".to_string();
这里要加安全判断。不然可能会出事。

2023-07-12 17:13 UTC, fslongjin commented on src/parser/task.rs
> +        return format!("{}-{}", self.name.replace(" ", "_"), self.version);
应该是像下面那个[name_version_uppercase](https://opengrok.ringotek.cn/s?refs=name_version_uppercase&project=DADK)函数里面那样替换。因为有个全局替换表。

2023-07-13 07:00 UTC, fslongjin requested changes

2023-07-13 16:54 UTC, Chiichen commented on src/parser/task.rs
> +        return format!("{}-{}", self.name.replace(" ", "_"), self.version);
已替换，全局替换后cache文件夹内的文件夹都是形如n_a_m_e-0_0_1的文件夹格式，之前是形如dadk config中的taskname-version

2023-07-13 16:55 UTC, Chiichen commented on src/executor/source.rs
> +        remove_dir_all(path.join(&self.filename)).map_err(|e| e.to_string())?;
这个函数实际上是标准库里的函数，我没标注清楚，已经规范了所有类似的函数调用格式。把其它地方我自定义的散装函数归类到FileUtils里了

2023-07-13 16:55 UTC, Chiichen commented on src/executor/source.rs
> +    pub fn install(&self, target_dir: &CacheDir) -> Result<(), String> {
已改为 download_unzip

2023-07-13 16:55 UTC, Chiichen commented on LICENSE
已修改

2023-07-13 16:56 UTC, Chiichen commented on src/executor/mod.rs
> +                        let mut cmd = "cp -r ".to_string();
后续的所有命令行操作都改为了rust标准库或第三方库实现(reqwest实现下载和zip实现解压)

2023-07-13 17:05 UTC, Chiichen commented
## TL;DR
在执行代码源和预编译源的archive类型任务中，会有一个获取压缩文件开始前创建的，成功完成解压，进入 build 流程前删除的临时文件夹，现在的逻辑是如果检测到缓存路径中有这个文件夹，就认为上次获取压缩文件失败，会清空任务对应的 cache 目录。如果这个临时文件夹不存在，且缓存文件不为空，就认为上次获取文件成功，就在现有cache目录的基础上直接进行 build。

## 问题概述
换言之，如果你下载的压缩文件内的代码 build 失败了，请清空任务对应的 source cache 目录，否则会一直在之前获取的错误代码的基础上一直 build

2023-07-15 06:14 UTC, fslongjin requested changes

2023-07-15 06:14 UTC, fslongjin commented on src/utils/file.rs
> +        let file_name = tempurl.path_segments().unwrap().last().unwrap();
这里不应该直接unwrap哈哈，应该对出错的地方，报出错误信息。可以用expect方法

2023-07-28 09:23 UTC, fslongjin approved these changes

2023-07-28 09:24 UTC, merged