target管理
DragonOS-Community/DADK pull request #14
Opened 2023-10-08 08:27 UTC by Jomocool

新增target抽象层：
- 设置DADK_RUST_TARGET_FILE环境变量
- 将target文件放入/tmp中对应的dadk文件夹
- make clean后删掉/tmp中对应的dadk文件夹

2023-10-11 03:11 UTC, Jomocool commented on src/console/new_config.rs
> +    fn input_rust_target(&self, name: &str, version: &str) -> Result<Option<String>, ConsoleError> {
那我应该理解错了，我以为这里会读取dadk文件的字段，然后我的理解是，如果没有rust_target字段又去读了rust_target，就会提前多读了一个字段，导致后面的字段值都错位读到前一个字段上面去了

2023-10-11 03:12 UTC, Jomocool commented on src/executor/mod.rs
> +        if let Some(rust_target) = self.entity.task().rust_target.clone() {
好的

2023-10-11 03:18 UTC, Jomocool commented on src/executor/target.rs
> +        let default_target = format!("{}{}", dragonos_path, "/user/dadk/target.json");
这里我没明白，因为我以为这个target文件会内置在DragonOS的user/dadk下。如果由dadk维护的话，是不是意味着用户在cargo install dadk的时候，就把这个target文件拷贝到/tmp下，然后再设置一个环境变量？

2023-10-11 03:22 UTC, Jomocool commented on src/executor/target.rs
> +pub struct Target {
好的好的

2023-10-23 14:10 UTC, fslongjin requested changes

2023-10-23 14:10 UTC, fslongjin commented on src/executor/mod.rs
> +pub const TARGET_BINARY: &'static [u8] = include_bytes!("target.json");
这样是不正确的：
1. 我们的target应当使用目标三元组去标识，比如这个文件其实是`x86_64-unknown-dragonos`这个目标。
2. 将来会有多个内置target，因此内置target也有自己的名称。需要使用一个元组去存储name和binary的数据，按照名字去匹配。
3. 这个json文件放在外面的`/config/taregts/rust`目录下面，然后在taregt manager那里导入会比较好。

2023-10-23 14:10 UTC, fslongjin commented on src/executor/target.rs
> +pub struct TargetManager {
按照现在的写法，这个对象叫做`Target`就行了

2023-10-23 14:10 UTC, fslongjin commented on src/executor/mod.rs
> +            let path: PathBuf = self
这里写复杂了，这两个信息都属于`Target`，不要在外面这executor的地方，做这种“从target读信息，然后再传入target的成员函数”的写法。设置环境变量的工作只要封装成target的成员函数`prepare_env`就行了。

2023-10-23 14:10 UTC, fslongjin commented on src/executor/target.rs
> +        return rust_target.contains('/') || rust_target.contains('\\');
这是不正确的，因为用户也可以把`target.json`放置在当前目录下，那就没有`/`或者`\`了。
正确做法是，判断是否包含`.`

因为内置的target,使用目标三元组去标识，是不会带有`.json`这样的字符的。

2023-11-08 08:03 UTC, fslongjin approved these changes

2023-11-08 08:04 UTC, merged