feat(dadk-user): 编译缓存优化
DragonOS-Community/DADK pull request #73
Opened 2024-11-06 16:26 UTC by Jomocool

2024-11-08 02:32 UTC, fslongjin requested changes

2024-11-08 02:32 UTC, fslongjin commented on dadk-user/src/executor/mod.rs
> +                    && last_modified_time(self.entity.file_path()) < *build_time
我感觉可以写个函数，在dfs的时候就检查一下跟Build time的关系，提前剪枝，会快一些。

2024-11-08 02:32 UTC, fslongjin commented on dadk-user/src/executor/mod.rs
> +        }
这只检查了最顶上那层文件夹，如果是文件夹内部的文件被更改了，是检测不到的。

2024-11-08 02:33 UTC, Jomocool commented on dadk-user/src/executor/mod.rs
> +                    && last_modified_time(self.entity.file_path()) < *build_time
OK

2024-11-08 02:36 UTC, Jomocool commented on dadk-user/src/executor/mod.rs
> +        }
应该可以吧，如果是目录的话会递归

2024-11-08 16:53 UTC, Jomocool commented on dadk-user/src/executor/mod.rs
> +        }
外部entry和内部entry同名了，我改一下

2024-11-10 12:02 UTC, fslongjin requested changes

2024-11-10 12:02 UTC, fslongjin commented on dadk-user/src/executor/mod.rs
> +
感觉可以把这个改为`last_modified_time`的返回值呀

2024-11-10 12:07 UTC, Jomocool commented on dadk-user/src/executor/mod.rs
> +
OK

2024-11-10 15:22 UTC, fslongjin approved these changes

2024-11-10 15:22 UTC, merged